"""
PLOFA 26/27 — PLAYER ACTION MAPS
=====================================
player_maps.py

Per-player pass map, carry map, and dribble map — built entirely from
REAL individual event coordinates already sitting in the timeline
(location_x/y, end_x/end_y, outcome), not estimation and not averages.
Every MatchEvent generated by event_chain.py already carries exact start/
end coordinates for passes and carries, and exact location + outcome for
dribbles — this module is the first thing to actually plot them at the
individual-event level instead of collapsing them into an average dot.

Color language (SofaScore-inspired, PLOFA dark theme):
    Pass map:
        completed pass (incl. progressive / switch of play)  -> teal
        incomplete pass                                       -> red
        cross (attempted + completed)                          -> purple
        key pass (setup pass that created a shot, derived by the
        Chance Creation Ledger from the real timeline)            -> gold, thicker, star at the receiving end
    Carry map:
        successful carry                                        -> white, dashed
        unsuccessful carry (led to a turnover)                    -> white, dashed, faint
    Dribble map:
        successful dribble                                        -> green dot
        unsuccessful dribble                                        -> red dot

Tackles/interceptions maps are intentionally NOT included yet — scoped
for a follow-up checkpoint.
"""

from __future__ import annotations
from typing import Dict, List, Optional, Tuple

import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
import matplotlib.patheffects as pe
from mplsoccer import Pitch

from match_engine import MatchEvent, EventType, MatchResult


# ─────────────────────────────────────────────
# COLORS
# ─────────────────────────────────────────────

class ActionMapColors:
    PASS_COMPLETE   = "#00B4D8"   # teal
    PASS_INCOMPLETE = "#E63946"   # red
    CROSS           = "#B388FF"   # purple
    KEY_PASS        = "#F5C518"   # gold
    CARRY           = "#FFFFFF"   # white
    DRIBBLE_SUCCESS = "#2DC653"   # green
    DRIBBLE_FAIL    = "#E63946"   # red

    PITCH_GREEN = "#2D5016"
    PITCH_LINE  = "#FFFFFF"
    BG_DARK     = "#0D0D0D"
    TEXT        = "#F0F0F0"
    MUTED       = "#8A8A8A"


PASS_LIKE = (EventType.PASS, EventType.PROGRESSIVE_PASS, EventType.SWITCH_OF_PLAY,
             EventType.THROUGH_BALL)
CROSS_LIKE = (EventType.CROSS_ATTEMPT, EventType.CROSS_SUCCESS)
CHANCE_LIKE = (EventType.CHANCE_CREATED, EventType.BIG_CHANCE_CREATED)
DRIBBLE_LIKE = (EventType.DRIBBLE_SUCCESS, EventType.DRIBBLE_FAIL)


def _player_events(timeline: List[MatchEvent], player_name: str,
                    types: Tuple[EventType, ...]) -> List[MatchEvent]:
    return [e for e in timeline if e.player == player_name and e.event_type in types]


def _to_draw_coords(x: Optional[float], y: Optional[float]) -> Tuple[float, float]:
    """Convert our 105x68 pitch coords to mplsoccer's statsbomb 120x80 space."""
    if x is None or y is None:
        return 60.0, 40.0
    return x / 105 * 120, y / 68 * 80


# ─────────────────────────────────────────────
# INDIVIDUAL MAP DRAWERS
# Each takes an existing ax + pitch so they can be composed into one
# dashboard OR saved standalone.
# ─────────────────────────────────────────────

def resolve_key_pass_plot_endpoints(event: MatchEvent, ledger_record, index: int):
    """Return the cleanest receiver-end point for a key-pass visual.

    For normal passes, use the actual pass destination. For missing endpoints,
    prefer the shot/receiver point that the ledger identified as the setup pass's
    target (typically the shooter location or the point just before the shot),
    and only then fall back to the pass origin.
    """
    if event.end_x is not None and event.end_y is not None:
        return event.end_x, event.end_y
    if getattr(ledger_record, "pass_event_index", -1) == index:
        shot_x = getattr(ledger_record, "shot_x", None)
        shot_y = getattr(ledger_record, "shot_y", None)
        if shot_x is not None and shot_y is not None:
            return shot_x, shot_y
        if getattr(ledger_record, "pass_end_x", None) is not None:
            return ledger_record.pass_end_x, ledger_record.pass_end_y
    if getattr(event, "secondary_player", None) and event.location_x is not None:
        return event.location_x, event.location_y
    return event.location_x, event.location_y


def draw_pass_map(ax, pitch: Pitch, timeline: List[MatchEvent], player_name: str,
                  ledger=None):
    """
    Draw a player's passes, crosses and KEY PASSES.

    Key passes are the REAL setup passes identified by the Chance Creation
    Ledger (the final completed delivery before a shot — Opta's definition),
    NOT the fabricated CHANCE_CREATED events the engine used to emit. When no
    ledger is supplied one is computed from the timeline on the fly.
    """
    if ledger is None:
        from chance_creation import ChanceCreationLedger
        ledger = ChanceCreationLedger(timeline).compute()
    kp_indexes = set(ledger.shot_assist_event_indexes)
    kp_events = [e for i, e in enumerate(timeline)
                 if e.player == player_name and i in kp_indexes]
    kp_ids = {id(e) for e in kp_events}
    kp_lookup = {i: r for i, r in enumerate(ledger.records) if r.pass_event_index in kp_indexes}

    passes  = [e for e in _player_events(timeline, player_name, PASS_LIKE)
               if id(e) not in kp_ids]
    crosses = [e for e in _player_events(timeline, player_name, CROSS_LIKE)
               if id(e) not in kp_ids]

    comp_x1, comp_y1, comp_x2, comp_y2 = [], [], [], []
    inc_x1, inc_y1, inc_x2, inc_y2 = [], [], [], []

    for e in passes:
        x1, y1 = _to_draw_coords(e.location_x, e.location_y)
        x2, y2 = _to_draw_coords(e.end_x, e.end_y)
        if e.outcome:
            comp_x1.append(x1); comp_y1.append(y1); comp_x2.append(x2); comp_y2.append(y2)
        else:
            inc_x1.append(x1); inc_y1.append(y1); inc_x2.append(x2); inc_y2.append(y2)

    if comp_x1:
        pitch.arrows(comp_x1, comp_y1, comp_x2, comp_y2, ax=ax,
                      color=ActionMapColors.PASS_COMPLETE, alpha=0.75,
                      width=1.4, headwidth=5, headlength=5, zorder=3)
    if inc_x1:
        pitch.arrows(inc_x1, inc_y1, inc_x2, inc_y2, ax=ax,
                      color=ActionMapColors.PASS_INCOMPLETE, alpha=0.65,
                      width=1.4, headwidth=5, headlength=5, zorder=3)

    cross_x1, cross_y1, cross_x2, cross_y2 = [], [], [], []
    for e in crosses:
        x1, y1 = _to_draw_coords(e.location_x, e.location_y)
        x2, y2 = _to_draw_coords(e.end_x, e.end_y)
        cross_x1.append(x1); cross_y1.append(y1); cross_x2.append(x2); cross_y2.append(y2)
    if cross_x1:
        pitch.arrows(cross_x1, cross_y1, cross_x2, cross_y2, ax=ax,
                      color=ActionMapColors.CROSS, alpha=0.85,
                      width=1.4, headwidth=5, headlength=5, zorder=4)

    kp_x1, kp_y1, kp_x2, kp_y2 = [], [], [], []
    kp_star_x, kp_star_y = [], []
    for i, e in enumerate(timeline):
        if e.player != player_name or i not in kp_indexes:
            continue
        ledger_record = next((r for r in ledger.records if r.pass_event_index == i), None)
        x1, y1 = _to_draw_coords(e.location_x, e.location_y)
        x2, y2 = resolve_key_pass_plot_endpoints(e, ledger_record, i)
        x2, y2 = _to_draw_coords(x2, y2)
        kp_x1.append(x1); kp_y1.append(y1); kp_x2.append(x2); kp_y2.append(y2)
        if e.end_x is None or e.end_y is None:
            # Even when the pass has no recorded landing spot, the star should sit
            # on the receiver/shot point rather than the pass origin.
            kp_star_x.append(x2); kp_star_y.append(y2)
    if kp_x1:
        pitch.arrows(kp_x1, kp_y1, kp_x2, kp_y2, ax=ax,
                      color=ActionMapColors.KEY_PASS, alpha=0.95,
                      width=1.4, headwidth=6, headlength=6, zorder=5)
        pitch.scatter(kp_x2, kp_y2, ax=ax, s=90, marker="*",
                       color=ActionMapColors.KEY_PASS, edgecolors="black",
                       linewidths=0.6, zorder=6)
    if kp_star_x:
        pitch.scatter(kp_star_x, kp_star_y, ax=ax, s=90, marker="*",
                       color=ActionMapColors.KEY_PASS, edgecolors="black",
                       linewidths=0.6, zorder=6)

    comp_ct, inc_ct = len(comp_x1), len(inc_x1)
    total = comp_ct + inc_ct
    acc = round(comp_ct / total * 100, 1) if total else 0.0
    ax.set_title(
        f"Passes: {comp_ct}/{total} ({acc}%)   |   Crosses: {len(cross_x1)}   |   "
        f"Shot Assists: {len(kp_events)}",
        color=ActionMapColors.TEXT, fontsize=10, fontweight="bold", pad=8
    )


def draw_carry_map(ax, pitch: Pitch, timeline: List[MatchEvent], player_name: str):
    carries = _player_events(timeline, player_name, (EventType.CARRY,))
    n_success = 0
    for e in carries:
        if e.end_x is None or e.end_y is None:
            continue
        x1, y1 = _to_draw_coords(e.location_x, e.location_y)
        x2, y2 = _to_draw_coords(e.end_x, e.end_y)
        ok = bool(e.outcome)
        n_success += 1 if ok else 0
        ax.annotate(
            "", xy=(x2, y2), xytext=(x1, y1),
            arrowprops=dict(
                arrowstyle="-|>", color=ActionMapColors.CARRY,
                linestyle=(0, (4, 3)),  # dashed
                lw=1.6 if ok else 1.1,
                alpha=0.85 if ok else 0.35,
                shrinkA=0, shrinkB=0,
            ),
            zorder=4,
        )
    ax.set_title(
        f"Carries: {n_success}/{len(carries)} progressed cleanly",
        color=ActionMapColors.TEXT, fontsize=10, fontweight="bold", pad=8
    )


def draw_dribble_map(ax, pitch: Pitch, timeline: List[MatchEvent], player_name: str):
    dribbles = _player_events(timeline, player_name, DRIBBLE_LIKE)
    succ_x, succ_y, fail_x, fail_y = [], [], [], []
    for e in dribbles:
        x, y = _to_draw_coords(e.location_x, e.location_y)
        if e.event_type == EventType.DRIBBLE_SUCCESS:
            succ_x.append(x); succ_y.append(y)
        else:
            fail_x.append(x); fail_y.append(y)

    if succ_x:
        pitch.scatter(succ_x, succ_y, ax=ax, s=130, color=ActionMapColors.DRIBBLE_SUCCESS,
                       edgecolors="white", linewidths=1.2, alpha=0.9, zorder=5)
    if fail_x:
        pitch.scatter(fail_x, fail_y, ax=ax, s=110, color=ActionMapColors.DRIBBLE_FAIL,
                       edgecolors="white", linewidths=1.0, alpha=0.75, marker="X", zorder=5)

    total = len(succ_x) + len(fail_x)
    pct = round(len(succ_x) / total * 100, 1) if total else 0.0
    ax.set_title(
        f"Dribbles: {len(succ_x)}/{total} completed ({pct}%)",
        color=ActionMapColors.TEXT, fontsize=10, fontweight="bold", pad=8
    )


# ─────────────────────────────────────────────
# PUBLIC ENTRY POINTS
# ─────────────────────────────────────────────

def _new_pitch_ax(fig, pos, half: bool = False):
    pitch = Pitch(pitch_type="statsbomb", pitch_color=ActionMapColors.PITCH_GREEN,
                  line_color=ActionMapColors.PITCH_LINE, half=half, line_zorder=2)
    ax = fig.add_subplot(pos)
    pitch.draw(ax=ax)
    return pitch, ax


def plot_player_dashboard(timeline: List[MatchEvent], player_name: str,
                           team: str, position: str, filepath: str,
                           team_color: str = "#00B4D8", ledger=None):
    """
    One PNG per player: pass map | carry map | dribble map, side by side.
    Every arrow/dot on this figure is a REAL individual event from the
    timeline — nothing here is an average or an estimate. Key passes on the
    pass map are the real setup passes found by the Chance Creation Ledger.
    """
    fig = plt.figure(figsize=(21, 8), facecolor=ActionMapColors.BG_DARK)
    fig.suptitle(f"{player_name}  ({position}, {team})", color=team_color,
                 fontsize=16, fontweight="bold", y=0.99)

    pitch1, ax1 = _new_pitch_ax(fig, 131)
    draw_pass_map(ax1, pitch1, timeline, player_name, ledger=ledger)

    pitch2, ax2 = _new_pitch_ax(fig, 132)
    draw_carry_map(ax2, pitch2, timeline, player_name)

    pitch3, ax3 = _new_pitch_ax(fig, 133)
    draw_dribble_map(ax3, pitch3, timeline, player_name)

    legend_elements = [
        mpatches.Patch(color=ActionMapColors.PASS_COMPLETE, label="Pass completed"),
        mpatches.Patch(color=ActionMapColors.PASS_INCOMPLETE, label="Pass incomplete"),
        mpatches.Patch(color=ActionMapColors.CROSS, label="Cross"),
        mpatches.Patch(color=ActionMapColors.KEY_PASS, label="Key pass (shot setup)"),
        mpatches.Patch(color=ActionMapColors.CARRY, label="Carry"),
        mpatches.Patch(color=ActionMapColors.DRIBBLE_SUCCESS, label="Dribble won"),
        mpatches.Patch(color=ActionMapColors.DRIBBLE_FAIL, label="Dribble lost"),
    ]
    fig.legend(handles=legend_elements, loc="lower center", ncol=7,
               facecolor="#1A1A2E", labelcolor=ActionMapColors.TEXT,
               fontsize=8.5, framealpha=0.85)

    plt.tight_layout(rect=[0, 0.06, 1, 0.94])
    plt.savefig(filepath, dpi=150, bbox_inches="tight", facecolor=ActionMapColors.BG_DARK)
    plt.close(fig)
    return filepath


def plot_single_map(kind: str, timeline: List[MatchEvent], player_name: str,
                     filepath: str, half: bool = False):
    """Standalone single-panel version (kind: 'pass' | 'carry' | 'dribble')."""
    drawer = {"pass": draw_pass_map, "carry": draw_carry_map, "dribble": draw_dribble_map}[kind]
    fig = plt.figure(figsize=(8, 10.5), facecolor=ActionMapColors.BG_DARK)
    pitch, ax = _new_pitch_ax(fig, 111, half=half)
    drawer(ax, pitch, timeline, player_name)
    plt.tight_layout()
    plt.savefig(filepath, dpi=150, bbox_inches="tight", facecolor=ActionMapColors.BG_DARK)
    plt.close(fig)
    return filepath


# ─────────────────────────────────────────────
# WIRING GUIDE
# ─────────────────────────────────────────────

WIRING_GUIDE = """
WIRING player_maps.py INTO exporter.py
═══════════════════════════════════════

Add to PLOFAExporter:

    from player_maps import plot_player_dashboard

    def plot_all_player_dashboards(self, base_path: str, min_minutes: int = 1):
        import os
        folder = os.path.join(base_path, "player_maps")
        os.makedirs(folder, exist_ok=True)
        for name, s in self.accumulator.stats.items():
            if s["minutes_played"] < min_minutes:
                continue
            color = self.home_color if s["team"] == self.config.home_team else self.away_color
            safe = name.replace(" ", "_")
            plot_player_dashboard(
                self.result.timeline, name, s["team"], s["position"],
                f"{folder}/{safe}_actions.png", team_color=color
            )

Call it from export_all() alongside the existing plot_* calls, or on
demand for just your soul players (e.g. Percy) to keep output volume
sane during testing.
"""
