"""
tests/test_dna_awareness_shots.py — gate for the two 2026-10-05 DNA fixes.

FIX 1  `geometric_awareness` is generated by `_build_mental` (player_dna.py).
        Before: declared on MentalAttributes, given bands by EIGHT archetype
        templates, and never assigned by any builder — so it read 50.0 for
        every player ever created. Three LIVE shape rules in
        position_engine.py consumed it and were inert:
          :3292  CAM pocket blend bonus   was exactly 0.0
          :3431  midfielder half-space    needed >= 55, never fired
          :3519  attacker drift           ran at a flat 0.091

FIX 2  `_shot_on_target_prob` (event_chain.py) reads `effective_finishing` /
        `effective_composure` instead of the raw attributes, so form and
        fatigue reach shooting. `effective_composure` is new.

WHY A NEW FILE, and the lesson behind it. The existing suites are GREEN about
this. `tests/test_positional_realism.py` and `tests/test_shot_blocking.py` both
construct a `_FakeDNA` that sets `mental.geometric_awareness` BY HAND, so they
exercise the shape rules against an awareness value the real builder never
produced — they pass against the 50.0 constant and would pass identically if
the builder emitted nonsense. A suite that is green and silent about a feature
is not evidence about that feature, which is the same conclusion the short-corner
work reached for the same reason.

So this file asserts the two things the fakes cannot:
  (1) the builder really produces a distribution, and it is gated, not uniform;
  (2) the shot path really reads the effective values.
"""
from __future__ import annotations

import os
import random
import sys
import unittest

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

import player_dna as PD  # noqa: E402
from player_dna import DNAFactory, MentalAttributes, PlayerDNA  # noqa: E402


POSITIONS = ["GK", "CB", "LB", "RB", "CDM", "CM", "CAM", "LW", "RW", "ST", "CF"]


def _build(n: int = 220, seed: int = 4242) -> list[PlayerDNA]:
    random.seed(seed)
    np.random.seed(seed)
    specs = list(PD.ArchetypeLibrary.SPECIALTY_ARCHETYPE_MAP.keys())
    out = []
    for i in range(n):
        pos = POSITIONS[i % len(POSITIONS)]
        age = random.randint(18, 37)
        out.append(DNAFactory.create(f"T{i}", pos, [random.choice(specs)], age=age))
    return out


class TestGeometricAwarenessIsGenerated(unittest.TestCase):
    """FIX 1 — the attribute exists, varies, and is selective."""

    @classmethod
    def setUpClass(cls) -> None:
        cls.dnas = _build()

    def test_it_is_not_the_dataclass_default_any_more(self):
        """The regression itself: 50.0 on every player, forever."""
        vals = {d.mental.geometric_awareness for d in self.dnas}
        self.assertGreater(
            len(vals), 50,
            f"geometric_awareness is effectively constant ({sorted(vals)[:5]}) — "
            "it is back on the dataclass default and the three shape rules are "
            "inert again",
        )

    def test_every_outfielder_position_gets_a_value(self):
        """GK too — the builder must not skip it for a subset of positions."""
        for pos in POSITIONS:
            vals = [d.mental.geometric_awareness for d in self.dnas if d.position == pos]
            self.assertTrue(vals, f"no players built for {pos}")
            self.assertTrue(
                any(v != 50.0 for v in vals),
                f"{pos} all read exactly 50.0",
            )

    def test_archetype_templates_reach_the_player(self):
        """A regista's 80-91 template band must not be flattened to the default.

        This is the part a faked-DNA test can never see: the templates already
        specified this field, so the fix is really about honouring them.
        """
        regista = PD.ArchetypeLibrary.ARCHETYPES["regista"]
        lo, hi = regista["mental.geometric_awareness"]
        random.seed(99)
        np.random.seed(99)
        got = [
            DNAFactory.create(f"R{i}", "CM", ["playmaker"], age=24).mental.geometric_awareness
            for i in range(60)
        ]
        in_band = sum(1 for v in got if lo <= v <= hi)
        self.assertGreater(
            in_band / len(got), 0.55,
            f"regista band {regista['mental.geometric_awareness']} reached only "
            f"{in_band}/{len(got)} of players — the template is not being read",
        )

    def test_outfielders_still_clear_the_gates_but_not_by_construction(self):
        """PositionEngine.py:3431 (>= 55) and :3519 (>= 50) are now reachable.

        WHAT THIS DOES NOT CLAIM, and why — this assertion was WRONG in its
        first form and the correction is the point.

        The first version asserted that the gates should SELECT, i.e. reject
        some fraction of midfielders. Measurement said midfielders clear >= 55
        at 100.0%, and the cause is NOT the default band: 42% of players land on
        one of the eight templates that name this field, and the LOWEST template
        floor is 60 — already above the 55 gate. So for that population the gate
        was always satisfiable, and the first version's suggested remedy
        ("lower the default band") could not have worked: recomputing with
        default bands of (40,60), (45,65) and (50,60) moves the combined
        midfielder clear rate to 52.8% / 67.1% / 64.4% only by dragging the
        TEMPLATE population down, and (55,74) — the real shipped band before
        this correction — sat at 97.0%.

        So the honest statement is narrower: the gates are no longer vacuous
        because of a constant, and outfield positions clear them as a
        CONSEQUENCE of the distribution rather than by construction. Defenders
        and goalkeepers, who are NOT gate consumers, still straddle both
        thresholds — which is the observable proof that the attribute varies
        and the thresholds mean something.

        Whether :3431 SHOULD select is a design question about a tuned
        threshold, and per the CORNER STEP 6 discipline it is not answered by
        tuning the band or the gate until a measurement says the resulting shape
        is better. See _diag_awareness_gates.py section D.
        """
        def clear_rate(positions, threshold):
            vals = [d.mental.geometric_awareness for d in self.dnas
                    if d.position in positions]
            self.assertTrue(vals, f"no players for {positions}")
            return sum(1 for v in vals if v >= threshold) / len(vals)

        # Consumers of the two rules: midfielders (:3431) and attackers (:3519).
        self.assertGreater(clear_rate(("CDM", "CM", "CAM"), 55.0), 0.90)
        self.assertGreater(clear_rate(("LW", "RW", "ST", "CF"), 50.0), 0.70)
        # NOT consumers. If these also cleared everything, the gates would carry
        # no information about the distribution at all.
        for pos in ("CB", "LB", "RB", "GK"):
            vals = [d.mental.geometric_awareness for d in self.dnas
                    if d.position == pos]
            self.assertTrue(vals)
            below = sum(1 for v in vals if v < 55.0) / len(vals)
            self.assertGreater(
                below, 0.15,
                f"{pos} no longer straddles the thresholds (only {below:.0%} "
                "below 55) — the attribute has collapsed to a high constant "
                "again, which is the same defect in the other direction",
            )

    def test_a_constant_other_than_50_would_also_be_wrong(self):
        """A constant is a constant, whatever its value.

        Guards the *shape* of the regression rather than one number. A future
        edit that replaces the `_attr` call with a hard-coded 60.0 would look
        like a fix — the attribute would stop reading 50.0 and the three shape
        rules would start firing — while being the same inertness one value
        over. Mutation M1b in _diag_dna_guard.py is exactly this.
        """
        random.seed(8080)
        np.random.seed(8080)
        vals = {
            DNAFactory.create(f"K{i}", "CM", [], age=26).mental.geometric_awareness
            for i in range(150)
        }
        self.assertGreater(
            len(vals), 20,
            f"only {len(vals)} distinct values — the field has been replaced by a "
            "constant, which restores the original defect at a different value",
        )

    def test_the_default_band_is_the_house_mental_default(self):
        """Pins the (50, 70) default, which is a MEASURED decision, not a style choice.

        Added because the negative control (_diag_dna_guard.py, mutation M2)
        showed that restoring the rejected (55, 74) band left the whole file
        GREEN. The other tests all still passed at (55, 74), which means the
        band — the single most consequential choice in this fix — was pinned by
        nothing at all. A test that cannot fail is not a test, and the way to
        find out is to run the negative control, not to reason about it.

        Why (50, 70): it is the band five of this builder's other ten mental
        fields already use (vision, composure, decisions, positioning,
        anticipation, concentration, bravery). The first attempt used
        work_rate's (55, 74) on the argument that the eight named template
        bands are 60-93 and therefore mean "above average". Measurement killed
        it — see test_outfielders_still_clear_the_gates_but_not_by_construction
        for why the template population, not the default band, is what makes
        those gates pass, and _diag_awareness_gates.py section C for the sweep.
        """
        random.seed(5150)
        np.random.seed(5150)
        # No specialties -> the default band applies. Age 28 is inside
        # AGE_CURVE[range(27, 30)] == 1.00, the peak bracket, so the draw is the
        # band itself undiluted. Age 30 is range(30, 33) == 0.97 and would read
        # 48.7 at the floor — the multiplier is not a rounding detail here.
        self.assertEqual(DNAFactory.AGE_CURVE[range(27, 30)], 1.00,
                         "the age curve moved; this test's age choice is stale")
        vals = [
            DNAFactory.create(f"D{i}", "CB", [], age=28).mental.geometric_awareness
            for i in range(300)
        ]
        self.assertTrue(vals)
        self.assertAlmostEqual(min(vals), 50.0, delta=0.5,
                               msg="default band floor is not 50 — the band changed")
        self.assertAlmostEqual(np.median(vals), 60.0, delta=1.0,
                               msg="default band is not centred on 60")
        self.assertAlmostEqual(max(vals), 70.0, delta=0.5,
                               msg="default band ceiling is not 70 — the band changed")
        # :3431 needs >= 55, which sits strictly inside the band, so roughly
        # 40% of the default population is rejected by it. The :3519 gate is
        # >= 50, i.e. exactly the band's floor, so from the DEFAULT population
        # almost nobody is rejected. That asymmetry is a property of the two
        # tuned thresholds, recorded here so it is not mistaken for a bug in
        # the band — see _diag_awareness_gates.py section D.
        # Uniform(50, 70) puts exactly 5/20 = 25.0% of the default population
        # below 55. The floor is asserted at 0.15, NOT at 0.25: a threshold
        # sitting on the theoretical value is a knife-edge that a 300-sample
        # draw crosses about half the time (measured 24.3%), and that is the
        # same trap as the CM assertion in AGENTS.md that fails by 1.5 cm.
        # The upper bound at 0.40 still catches a band that has been raised
        # toward the gate, which is the mutation this exists to catch.
        rejected = sum(1 for v in vals if v < 55.0) / len(vals)
        self.assertGreater(
            rejected, 0.15,
            f"only {rejected:.0%} of the default population is below the :3431 "
            "gate — the band floor has been raised toward the threshold",
        )
        self.assertLess(
            rejected, 0.40,
            f"{rejected:.0%} of the default population is below the :3431 gate — "
            "the band has been lowered, and the :3431 rule is firing for players "
            "the templates treat as spatially unaware",
        )

    def test_awareness_scales_the_steering_factors_continuously(self):
        """The point of the fix is a CONTINUOUS per-player weight, not a new
        constant. Both factors are transcribed from position_engine.py.
        """
        def mid_factor(ga: float) -> float:
            return max(0.0, min(1.0, (ga - 50.0) / 50.0))

        def att_factor(ga: float) -> float:
            return max(0.0, min(1.0, (ga - 45.0) / 55.0))

        # The exact pre-fix value for every player ever created, both rules.
        self.assertEqual(mid_factor(50.0), 0.0)
        self.assertAlmostEqual(att_factor(50.0), 0.0909, places=3)

        factors = [mid_factor(d.mental.geometric_awareness) for d in self.dnas]
        distinct = len({round(f, 4) for f in factors})
        self.assertGreater(
            distinct, 40,
            f"only {distinct} distinct midfielder factors — that is a constant "
            "with rounding on it, not a per-player weight",
        )
        # Spread across the range, not clustered at one end. The :3431 rule's
        # documented span is 0.0 to 1.0; a real population occupies the middle.
        self.assertGreater(max(factors), 0.40,
                           "no midfielder exceeds a 0.40 factor — check the bands")
        self.assertGreater(np.median(factors), 0.10,
                           "the median factor is ~0, i.e. the rule is inert again")

    def test_cam_pocket_bonus_is_now_non_zero_for_some_players(self):
        """position_engine.py:3292 — was exactly 0.0 for ALL players, ever."""
        def bonus(ga: float) -> float:
            return max(0.0, min(0.12, (ga - 50.0) / 350.0))

        bonuses = [bonus(d.mental.geometric_awareness) for d in self.dnas
                   if d.position == "CAM"]
        self.assertTrue(bonuses)
        self.assertGreater(
            np.median(bonuses), 0.02,
            "CAM blend bonus is still ~zero at the median — the :3292 rule has "
            "not started reading anything",
        )
        self.assertLessEqual(max(bonuses), 0.12 + 1e-9, "exceeds the documented cap")
        # The floor must remain REACHABLE by a low player, or the rule has become
        # a second constant. Defenders are the low tail of the distribution.
        allb = [bonus(d.mental.geometric_awareness) for d in self.dnas]
        self.assertGreaterEqual(min(allb), 0.0)
        self.assertLess(
            min(allb), 0.01,
            f"the lowest bonus in the whole squad is {min(allb):.4f} — the "
            "0.40 blend floor is no longer reachable by anyone",
        )


class TestShotPathReadsEffectiveAttributes(unittest.TestCase):
    """FIX 2 — form and fatigue reach shooting."""

    def _shooter(self, finishing: float, composure: float,
                 confidence: float, fatigue: float) -> PlayerDNA:
        dna = PlayerDNA(name="S", position="ST", age=25)
        dna.technical.finishing = finishing
        dna.mental.composure = composure
        dna.form.confidence = confidence
        dna.form.fatigue_level = fatigue
        return dna

    def test_effective_composure_exists_and_matches_the_documented_formula(self):
        """The new property mirrors effective_finishing exactly."""
        dna = self._shooter(75.0, 70.0, 80.0, 20.0)
        form = dna.form.form_multiplier
        fat = dna.form.fatigue_multiplier
        live = dna.live_performance_mult
        self.assertAlmostEqual(dna.effective_composure, 70.0 * form * fat * live, places=9)
        # And it agrees with effective_finishing on the multipliers used.
        self.assertAlmostEqual(
            dna.effective_finishing / 75.0, dna.effective_composure / 70.0, places=9)

    def test_effective_composure_is_neutral_at_default_form(self):
        dna = self._shooter(75.0, 70.0, 50.0, 0.0)
        self.assertAlmostEqual(dna.effective_composure, 70.0, places=9)
        self.assertAlmostEqual(dna.effective_finishing, 75.0, places=9)

    def test_the_shot_probability_reacts_to_form(self):
        """A hot striker converts better than a cold one, at equal attributes.

        Uses the real `_shot_on_target_prob`, so this fails if the shot path
        ever goes back to reading raw attributes.
        """
        from event_chain import AttackChain, SituationType
        import types

        hot = self._shooter(75.0, 70.0, 95.0, 0.0)
        cold = self._shooter(75.0, 70.0, 15.0, 0.0)

        def prob(dna: PlayerDNA) -> float:
            shooter = types.SimpleNamespace(name="S", dna=dna)
            return AttackChain._shot_on_target_prob(0.12, shooter, SituationType.OPEN_PLAY)

        p_hot, p_cold = prob(hot), prob(cold)
        self.assertGreater(
            p_hot, p_cold,
            "form does not reach _shot_on_target_prob — the shot path is reading "
            "raw attributes, not effective_finishing / effective_composure",
        )
        # Bounded: the attribute term carries 0.05 weight on two 0-100 values,
        # so this must be a single-digit percentage effect, not a rewrite.
        self.assertLess(
            p_hot - p_cold, 0.05,
            f"form moved on-target probability by {p_hot - p_cold:.4f} — the "
            "state term is meant to be a modifier, not a rewrite",
        )

    def test_the_shot_probability_reacts_to_fatigue(self):
        from event_chain import AttackChain, SituationType
        import types

        fresh = self._shooter(75.0, 70.0, 50.0, 0.0)
        tired = self._shooter(75.0, 70.0, 50.0, 100.0)

        def prob(dna: PlayerDNA) -> float:
            shooter = types.SimpleNamespace(name="S", dna=dna)
            return AttackChain._shot_on_target_prob(0.12, shooter, SituationType.OPEN_PLAY)

        self.assertGreater(
            prob(fresh), prob(tired),
            "fatigue does not reach _shot_on_target_prob",
        )

    def test_the_shot_path_does_not_read_the_raw_attributes(self):
        """Source-level pin, because a behavioural test cannot tell WHY.

        `test_the_shot_probability_reacts_to_form` passes if anything upstream
        of the function changes the number. This pins the actual reads, so a
        future edit that restores `dna.mental.composure` inside this function
        goes red even if some other change compensates numerically. Same
        reasoning as the AST guards in tests/test_chance_provenance.py.
        """
        import ast
        import inspect
        import textwrap

        from event_chain import AttackChain

        src = textwrap.dedent(inspect.getsource(AttackChain._shot_on_target_prob))
        tree = ast.parse(src)
        fn = tree.body[0]
        self.assertIsInstance(fn, (ast.FunctionDef,))

        reads: list[str] = []
        for node in ast.walk(fn):
            if isinstance(node, ast.Attribute):
                chain = []
                cur: ast.AST = node
                while isinstance(cur, ast.Attribute):
                    chain.append(cur.attr)
                    cur = cur.value
                if isinstance(cur, ast.Name):
                    chain.append(cur.id)
                    reads.append(".".join(reversed(chain)))

        # Suffix match, not exact: the receiver is a PlayerProfile so the real
        # chain is `shooter.dna.effective_finishing`. An exact-name match on
        # "dna.effective_finishing" would pass a test that pins the wrong string.
        # (A column/assertion whose expected value is weaker than the thing it
        # is checking is the same defect as the wrong-probe-key family.)
        def reads_dna(attr: str) -> bool:
            return any(r.endswith(f"dna.{attr}") for r in reads)

        self.assertTrue(reads_dna("effective_finishing"),
                        f"the shot path no longer reads effective_finishing: {reads}")
        self.assertTrue(reads_dna("effective_composure"),
                        f"the shot path no longer reads effective_composure: {reads}")
        for banned in ("technical.finishing", "mental.composure"):
            self.assertFalse(
                reads_dna(banned),
                f"the shot path reads raw dna.{banned} — form and fatigue cannot "
                "reach shooting through it",
            )


if __name__ == "__main__":
    unittest.main(verbosity=2)
