"""
PLOFA WORLD — the world layer of the World Football plan.

Phase 1–6 scope (world_layer audit §16):
    ids          stable canonical IDs + reversible name↔ID adapter
    model        typed world schemas (country, city, stadium, club, player, …)
    competition  generic league/cup competition framework with data-driven rules
    calendar     multi-competition fixture scheduler with a collision guarantee
    ledger       world-facing state store: one continuous player state across
                 every competition, with competition-scoped statistical lines
    ingest       engine → world translator (real MatchResult into the ledger)
    qualification promotion/relegation + continental entry, all rules as data
    testworld     the controlled two-federation test world (plan §17)
    month         the one-month integration test driver (plan §18)

Rule of this package: it never imports the live 26/27 pipeline at module
load and never writes to the authoritative season ledgers. Reuse of
existing PLOFA types (LeagueTable, FixtureList, MatchConfig) happens
lazily at call time via duck typing or explicit lazy imports.
"""
from world.ids import (
    ID_KINDS,
    ID_PREFIXES,
    NameAdapter,
    IdentityCollisionError,
    canonical_key,
    mint_id,
    player_key,
    build_plofa_adapter,
)
from world.model import (
    PitchDims,
    Country,
    City,
    Stadium,
    Club,
    Player,
    Manager,
    Referee,
    dump_json,
    load_json,
)
from world.competition import (
    Competition,
    CompetitionType,
    CompetitionRules,
    MatchContextFragment,
    LeagueCompetition,
    KnockoutCompetition,
    KnockoutTie,
    league_rules,
    cup_rules,
)
from world.calendar import (
    Calendar,
    CalendarConflictError,
    CompetitionEntry,
    PlannedFixture,
    SchedulePattern,
    Violation,
    WorldFixture,
    continental_midweek,
    cup_midweek,
    league_saturday,
)
from world.ledger import (
    CARRY_ACROSS_FIELDS,
    SCOPED_STAT_FIELDS,
    SCOPED_TO_CARRY_ACROSS,
    LedgerWriteError,
    MatchReport,
    PlayerMatchLine,
    PlayerState,
    WorldLedger,
    import_plofa_season_state,
    read_plofa_season_state,
)
from world.ingest import (
    apply_competition_context,
    apply_result,
    match_report_from_result,
    resolve_player_id,
)
from world.qualification import (
    Playoff,
    PromotionRelegationRules,
    QualificationEngine,
    QualificationError,
    QualificationRules,
    QualificationSlots,
    SeasonTransition,
    Standing,
    closed_league_rules,
    standings_from_warehouse,
    two_tier_rules,
)
from world.testworld import (
    CHAMPIONS_LEAGUE,
    COUNTRY,
    DOMESTIC_LEAGUE,
    EFL_CUP,
    ROSTER_CLUBS,
    TestWorld,
    build_test_world,
    month_fixtures,
)
from world.realworld import (
    CL_DIRECT_TO_R16,
    CL_FINAL,
    CL_LEAGUE_PHASE,
    CL_MATCHDAYS,
    EFL_CUP_FINAL,
    PL_MATCHDAYS,
    PL_SEASON_END,
    PL_SEASON_START,
    SEASON,
    champions_league_pattern,
    champions_league_rules,
    efl_cup_pattern,
    efl_cup_rules,
    fa_cup_pattern,
    fa_cup_rules,
    premier_league_pattern,
    premier_league_rules,
    season_summary,
)

__all__ = [
    "ID_KINDS",
    "ID_PREFIXES",
    "NameAdapter",
    "IdentityCollisionError",
    "canonical_key",
    "mint_id",
    "player_key",
    "build_plofa_adapter",
    "PitchDims",
    "Country",
    "City",
    "Stadium",
    "Club",
    "Player",
    "Manager",
    "Referee",
    "dump_json",
    "load_json",
    "Competition",
    "CompetitionType",
    "CompetitionRules",
    "MatchContextFragment",
    "LeagueCompetition",
    "KnockoutCompetition",
    "KnockoutTie",
    "league_rules",
    "cup_rules",
    "Calendar",
    "CalendarConflictError",
    "CompetitionEntry",
    "PlannedFixture",
    "SchedulePattern",
    "Violation",
    "WorldFixture",
    "continental_midweek",
    "cup_midweek",
    "league_saturday",
    "CARRY_ACROSS_FIELDS",
    "SCOPED_STAT_FIELDS",
    "SCOPED_TO_CARRY_ACROSS",
    "LedgerWriteError",
    "MatchReport",
    "PlayerMatchLine",
    "PlayerState",
    "WorldLedger",
    "import_plofa_season_state",
    "read_plofa_season_state",
    "apply_competition_context",
    "apply_result",
    "match_report_from_result",
    "resolve_player_id",
    "Playoff",
    "PromotionRelegationRules",
    "QualificationEngine",
    "QualificationError",
    "QualificationRules",
    "QualificationSlots",
    "SeasonTransition",
    "Standing",
    "closed_league_rules",
    "standings_from_warehouse",
    "two_tier_rules",
    "CHAMPIONS_LEAGUE",
    "COUNTRY",
    "DOMESTIC_LEAGUE",
    "EFL_CUP",
    "ROSTER_CLUBS",
    "TestWorld",
    "build_test_world",
    "month_fixtures",
    "CL_DIRECT_TO_R16",
    "CL_FINAL",
    "CL_LEAGUE_PHASE",
    "CL_MATCHDAYS",
    "EFL_CUP_FINAL",
    "PL_MATCHDAYS",
    "PL_SEASON_END",
    "PL_SEASON_START",
    "SEASON",
    "champions_league_pattern",
    "champions_league_rules",
    "efl_cup_pattern",
    "efl_cup_rules",
    "fa_cup_pattern",
    "fa_cup_rules",
    "premier_league_pattern",
    "premier_league_rules",
    "season_summary",
]